#!/bin/csh -f

#SBATCH --time=05:50:00
#SBATCH --job-name=numpy
#SBATCH --ntasks=40
#SBATCH --constraint=sky
#SBATCH -A j1008
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH -o Python2021-%j.out


#######################################################################
#                  System Environment Variables
#######################################################################

umask 022

#limit

source /usr/share/modules/init/csh
module purge

module load python/GEOSpyD/Min4.9.2_py3.9
#module load python/GEOSpyD/Ana2019.10_py3.7

echo '-------------------------'
echo 'Setting ouput file'
echo '-------------------------'
touch results.csv
python3 create_file_header.py

echo '-------------------------'
echo 'Look and say sequence'
echo '-------------------------'
python3 test_look_and_say.py 40

echo '-------------------------'
echo 'Count Unique Words in File'
echo '-------------------------'
python3 test_count_unique_words.py ./Data/bible.txt

echo '-------------------------'
echo 'Fibonacci Sequence'
echo '-------------------------'
python3 test_fibonacci.py 25
python3 test_fibonacci.py 35