#!/bin/csh -f

#SBATCH --time=05:50:00
#SBATCH --job-name=numpy
#SBATCH --ntasks=40
#SBATCH --constraint=sky
#SBATCH -A j1008
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH -o Python2021-%j.out


#######################################################################
#                  System Environment Variables
#######################################################################

umask 022

#limit

source /usr/share/modules/init/csh
module purge

module load python/GEOSpyD/Min4.9.2_py3.9
#module load python/GEOSpyD/Ana2019.10_py3.7
start=$(date +%s%N)

echo '-------------------------'
echo 'Setting ouput file'
touch results-docker-python.csv
python3 create_file_header.py docker

echo 'All set!'
echo '-------------------------'


echo '-------------------------'
echo 'Copy Matrix'
echo '-------------------------'
python3 test_copy_matrix.py 500 docker

echo '-------------------------'
echo 'Look and say sequence'
echo '-------------------------'
python3 test_look_and_say.py 40 docker

echo '-------------------------'
echo 'Count Unique Words in File'
echo '-------------------------'
python3 test_count_unique_words.py ./Data/bible.txt docker

echo '-------------------------'
echo 'Fibonacci Sequence'
echo '-------------------------'
python3 test_fibonacci.py 25 docker

echo '-------------------------'
echo 'Matrix Multiplication'
echo '-------------------------'
python3 test_matrix_multiplication.py 1500 docker

echo '-------------------------'
echo 'Belief Propagation'
echo '-------------------------'
python3 test_belief_propagation.py 250 docker

echo '-------------------------'
echo 'Markov Chain'
echo '-------------------------'
python3 test_markov_chain.py 5000 docker

echo '-------------------------'
echo 'Compute FFT'
echo '-------------------------'
python3 test_compute_FFT.py 10000 docker

echo '-------------------------'
echo 'Jacobi Iterative solver'
echo '-------------------------'
python3 test_laplace_jacobi_4.py 100 docker

echo '-------------------------'
echo 'Compute square root of a matrix'
echo '-------------------------'
python3 test_sqrt_matrix.py 1000 docker

echo 'Gauss Legendre quadrature'
echo '-------------------------'
python3 test_gauss_legendre_quadrature.py 50 docker

echo '-------------------------'
echo 'Evaluation of functions'
echo '-------------------------'
python3 test_evaluate_functions.py  80000 docker

echo '-------------------------'
echo 'Compute Munchausen Numbers'
echo '-------------------------'
python3 test_munchausen_number.py docker

echo '-------------------------'
echo 'Compute Pernicious Numbers'
echo '-------------------------'
python3 test_pernicious_numbers.py 100000 docker

echo '-------------------------'
echo 'Processing a collection of files'
echo '-------------------------'
python3 ./Data/create_nc4Files.py

python3 test_time_series_AOA.py
end=$(date +%s%N)
echo "Elapsed Time $(($(($end-$start))/1000000)) ms"
python3 writeTime.py "${start}" "${end}"
# time python3 test_time_series_AOA_multiproc.py 1
# time python3 test_time_series_AOA_multiproc.py 2
# time python3 test_time_series_AOA_multiproc.py 4
# time python3 test_time_series_AOA_multiproc.py 8
# time python3 test_time_series_AOA_multiproc.py 16
# time python3 test_time_series_AOA_multiproc.py 24
# time python3 test_time_series_AOA_multiproc.py 28


